version: "3.9"

services:

  redis:
    image: redis:latest
    hostname: redis

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"  
      - "15672:15672"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django
    command: bash scripts/run_app.sh
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - rabbitmq
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash scripts/run_celery.sh
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    depends_on:
      - rabbitmq