# Generated by Django 3.2.8 on 2022-01-31 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('countryCode', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('time', models.CharField(default=None, max_length=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('weight', models.IntegerField(default=None, null=True)),
                ('image', models.URLField(default=None, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvgrid.channel')),
                ('days', models.ManyToManyField(to='tvgrid.Day')),
                ('genres', models.ManyToManyField(to='tvgrid.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField(default=None, null=True)),
                ('number', models.IntegerField(default=None, null=True)),
                ('startTime', models.DateTimeField(default=None, null=True)),
                ('endTime', models.DateTimeField(default=None, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True)),
                ('image', models.URLField(default=None, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvgrid.show')),
            ],
        ),
    ]
