# Generated by Django 3.2.8 on 2022-01-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='countryCode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
