# Generated by Django 3.2.8 on 2022-01-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgrid', '0002_auto_20220131_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
