# Generated by Django 3.2.8 on 2022-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgrid', '0003_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='externalId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='externalId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='externalId',
            field=models.IntegerField(),
        ),
    ]
