# Generated by Django 3.2.8 on 2022-01-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgrid', '0005_alter_show_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
