# Generated by Django 3.2.8 on 2022-01-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvgrid', '0006_alter_episode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
