# Generated by Django 3.2.9 on 2021-12-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchHistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchHistory',
            new_name='history',
        ),
    ]
