# Generated by Django 3.2.9 on 2022-01-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchHistory', '0003_auto_20211218_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('preference', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='movieHistory',
        ),
    ]
