# Generated by Django 3.2.9 on 2022-02-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('watchHistory', '0004_auto_20220131_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
            preserve_default=False,
        ),
    ]
