# Generated by Django 3.2.9 on 2021-12-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPI', '0002_videocontent_imbdid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocontent',
            old_name='imbdID',
            new_name='imdbID',
        ),
    ]
