name: televis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - paho-mqtt 
  - ffmpeg-python 
  - django>=3.0,<4.0
  - pytest 
  - flake8 
  - djangorestframework 
  - requests
  - django-rest-swagger
  - django-celery-beat 
  - path 
  - pyyaml 
  - pillow 
  - celery[redis] 
  - django-celery-results 