# Generated by Django 3.2.5 on 2022-01-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('shazam_key', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('cover', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=120)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicAPI.song')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('uri', models.URLField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicAPI.song')),
            ],
        ),
    ]
