# Generated by Django 3.2.5 on 2022-01-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0002_alter_song_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalField',
            new_name='ExternalLink',
        ),
    ]
