# Generated by Django 4.0.2 on 2022-02-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicAPI', '0003_rename_externalfield_externallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
    ]
